// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SuntonESP32_example

#ifndef _SUNTONESP32_EXAMPLE_UI_H
#define _SUNTONESP32_EXAMPLE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"
#include "ui_helpers.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui____initial_actions0;

void ui_init(lv_disp_t *);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
